baseURL = "/"
locale = "zh-cn"
title = "RealMDFK45"
theme = "PaperMod"
paginate = 10
enableEmoji = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[menu]
  [[menu.main]]
    identifier = "travel"
    name = "游记"
    url = "/游记/"
    weight = 3

  [[menu.main]]
    identifier = "readingnotes"
    name = "读书笔记"
    url = "/读书笔记/"
    weight = 5

  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 10

  [[menu.main]]
    identifier = "categories"
    name = "分类"
    url = "/categories/"
    weight = 15

  [[menu.main]]
    identifier = "reading"
    name = "阅读档案"
    url = "/reading/"
    weight = 20

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 30

[params]
  mainSections = ["posts", "读书笔记", "游记"]
  description = "个人博客"
  defaultTheme = "auto"
  disableThemeToggle = false
  ShowDate = false
  ShowReadingTime = false
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = false
  ShowRssButtonInSectionTermList = true
  ShowAllPagesInArchive = true
  ShowPageNaviator = true
  ShowToc = true

  [params.label]
    text = "RealMDFK45"

  [params.homeInfoParams]
    Title = "Welcome to RealMDFK45's Blog"
    Content = "分享即收获 | 利人即利己 | 失败也是成长"